#!/usr/bin/env python3
"""Embed captured OPDS feeds unchanged for common tests without an iOS resource bundle."""
from pathlib import Path

root = Path(__file__).resolve().parents[2]
module = root / "feature/catalogue/ui/src/commonTest"
resources = module / "resources/linked-books"
target = module / "kotlin/com/retro99/catalogue/ui/browse/CapturedLinkFeeds.kt"
lines = ["// Generated by tools/ember-fixtures/embed_catalogue_feeds.py. Do not edit.",
         "package com.retro99.catalogue.ui.browse", "", "internal object CapturedLinkFeeds {", "    val xml = mapOf("]
for file in sorted(resources.glob("*.xml")):
    text = file.read_bytes().decode("utf-8")
    assert '"""' not in text
    text = text.replace("$", "${'$'}").replace("\r", "${'\\r'}")
    lines.append(f'        "{file.stem}" to """{text}""",')
lines += ["    )", "}", ""]
target.write_text("\n".join(lines))
print(target.relative_to(root))
