package com.retro99.statistics.domain.usecase

import com.github.michaelbull.result.Ok
import com.retro99.base.result.CompletableResult
import com.retro99.books.domain.model.BookType
import com.retro99.statistics.domain.StatisticsRepository
import com.retro99.statistics.domain.model.ReadingSessionDomainModel
import org.koin.core.annotation.Factory
import org.koin.core.annotation.Provided

/**
 * Saves sessions with at least 30 seconds of active reading or playback time.
 * Short accidental opens are ignored, irrespective of elapsed wall time or page turns.
 */
@Factory
class SaveReadingSessionUseCase(
    @Provided private val repository: StatisticsRepository,
) {
    suspend operator fun invoke(
        bookUuid: String,
        bookTitle: String,
        bookType: BookType,
        startTime: Long,
        endTime: Long,
        durationMs: Long,
        pagesRead: Int? = null,
        startProgression: Double? = null,
        endProgression: Double? = null,
        readingSpeedWpm: Int = DEFAULT_SESSION_READING_SPEED_WPM,
        recapSessionId: String? = null,
    ): CompletableResult {
        if (durationMs < MIN_SESSION_DURATION_MS) return Ok(Unit)
        val session = ReadingSessionDomainModel(
            id = 0, // Will be auto-generated by the database
            bookUuid = bookUuid,
            bookTitle = bookTitle,
            bookType = bookType,
            startTime = startTime,
            endTime = endTime,
            durationMs = durationMs,
            pagesRead = pagesRead,
            startProgression = startProgression,
            endProgression = endProgression,
            readingSpeedWpm = readingSpeedWpm,
            recapSessionId = recapSessionId,
        )
        return repository.saveReadingSession(session)
    }

    companion object {
        const val MIN_SESSION_DURATION_MS = 30_000L
    }
}

private const val DEFAULT_SESSION_READING_SPEED_WPM = 250
